// ==================== INTERFACE UTILISATEUR ====================
function filterProduction() { prodSearchTerm = document.getElementById('prod-search').value.toLowerCase(); renderProdPanel(); }
function filterDemand() { demandSearchTerm = document.getElementById('demand-search').value.toLowerCase(); renderDemandPanel(); }

function renderProdPanel() {
  let mf = freeMachinesCount(), ef = freeEmployeesCount(), av = getAvailableMachines();
  document.getElementById('prod-mfree').textContent = mf; document.getElementById('prod-mtotal').textContent = av.length;
  document.getElementById('prod-efree').textContent = ef; document.getElementById('prod-etotal').textContent = productionEmployeesCount();
  let filtered = products.filter(p => p.name.toLowerCase().includes(prodSearchTerm));
  document.getElementById('prod-grid').innerHTML = filtered.map(p => {
    let a = S.activeProductions[p.id], isA = !!a, machOk = isA || mf >= p.reqMachines, empOk = isA || ef >= p.reqEmployees, blocked = !isA && (!machOk || !empOk);
    let matRows = p.mats.map(m => { let n = p.qtyPerMatMap[m] || 1, s = S.materialsStock[m] || 0; return { mat: m, needed: n, stock: s, runs: Math.floor(s / n), ok: s >= n }; });
    let minRuns = matRows.length ? Math.min(...matRows.map(r => r.runs)) : 0;
    if (!machineSelections[p.id]) machineSelections[p.id] = Array(p.reqMachines).fill('');
    if (!isA && p.reqMachines > 0 && av.length >= p.reqMachines) { let used = new Set(); for (let i = 0; i < p.reqMachines; i++) if (!machineSelections[p.id][i]) { let a = av.find(m => !used.has(m.id)); if (a) { machineSelections[p.id][i] = a.id.toString(); used.add(a.id); } } }
    let machineSelectors = '';
    if (!isA && p.reqMachines > 0) { machineSelectors = '<div class="machine-selector"><div class="machine-selector-title">' + p.reqMachines + ' machine(s) :</div>'; for (let i = 0; i < p.reqMachines; i++) machineSelectors += `<div class="machine-select-row"><select onchange="updateMachineSelection(${p.id},${i},this.value)"><option value="">-- Choisir --</option>${av.map(m => `<option value="${m.id}" ${machineSelections[p.id][i] == m.id ? 'selected' : ''}>${m.name} (${m.usage}%)</option>`).join('')}</select></div>`; machineSelectors += '</div>'; }
    return `<div class="pcard"><div class="pcard-top"><span class="pcard-name">${p.name}</span><span class="pcard-status ${isA ? 'active' : blocked ? 'blocked' : 'idle'}">${isA ? '● En production' : blocked ? '✗ Ressources' : '○ En attente'}</span></div><div class="req-row"><span class="req-chip machines ${machOk || isA ? 'ok' : 'ko'}">⚙️ ${p.reqMachines}</span><span class="req-chip employees ${empOk || isA ? 'ok' : 'ko'}">👷 ${p.reqEmployees}</span><span class="req-chip time">⏱️ ${formatProductionTime(p.productionTimeGame)}/produit</span></div><div class="mats-section"><div class="mats-section-title">Matières (${p.mats.length})</div>${matRows.map(r => `<div class="mat-row"><span>${MAT_MAP[r.mat]?.icon || ''} ${r.mat}</span><span>${r.needed} → 1 produit</span><span style="color:${r.ok ? 'var(--green)' : 'var(--red)'}">${r.stock}</span><span>${r.runs} produits</span></div>`).join('')}<div>Possibles : <b>${minRuns}</b></div></div><div class="produce-section">${isA ? `<div>${a.cyclesDone}/${a.cyclesTotal} produits</div><div class="progress-section"><div class="progress-bar-container"><div class="progress-bar-fill" style="width:${Math.min(100, (Date.now() - a.cycleStartTime) / p.productionTimeReal * 100)}%"></div></div></div><button class="stop-btn" onclick="confirmStopProduction(${p.id},'${p.name}')">⏹ Arrêter</button>` : `<div class="prod-qty-row"><span>Produits :</span><button class="qty-btn" onclick="cqtyProd(${p.id},-1)">−</button><input class="qty-input" id="pqty-${p.id}" value="${Math.max(1, Math.min(minRuns, 5))}" min="1" max="${minRuns}"><button class="qty-btn" onclick="cqtyProd(${p.id},1)">+</button></div>${machineSelectors}<button class="produce-btn" ${blocked || !matRows.every(r => r.ok) || minRuns === 0 ? 'disabled' : ''} onclick="startProductionWithMachineSelection(${p.id})">${!machOk ? `⚙️ Manque ${p.reqMachines - mf}` : !empOk ? `👷 Manque ${p.reqEmployees - ef}` : minRuns === 0 ? '📦 Matières' : '▶ Lancer'}</button>`}</div></div>`;
  }).join('');
}

function updateMachineSelection(pid, i, v) { if (!machineSelections[pid]) machineSelections[pid] = []; machineSelections[pid][i] = v; }
function cqtyProd(id, d) { let i = document.getElementById(`pqty-${id}`); if (i) { let max = parseInt(i.max) || 999; i.value = Math.max(1, Math.min(max, (parseInt(i.value) || 1) + d)); } }
function startProductionWithMachineSelection(id) { let p = products.find(x => x.id == id); if (!p) return; let c = parseInt(document.getElementById(`pqty-${id}`)?.value) || 1; let s = (machineSelections[id] || []).filter(v => v !== '').map(v => parseInt(v)); if (s.length !== p.reqMachines || new Set(s).size !== s.length) { toast(`Sélectionnez ${p.reqMachines} machines distinctes`, 'err'); return; } startProduction(id, c, s); }

function renderDemandPanel() {
  let f = products.filter(p => p.name.toLowerCase().includes(demandSearchTerm));
  document.getElementById('demand-grid').innerHTML = f.map(p => { let d = S.productDemands[p.id] || p.baseDemand, pct = Math.min(100, Math.round(d / p.baseDemand * 100)), l = pct >= 70 ? 'high' : pct >= 30 ? 'medium' : 'low'; return `<div class="demand-card"><div class="demand-card-top"><span>${p.name}</span><span class="demand-card-badge ${l}">${l === 'high' ? 'Forte' : l === 'medium' ? 'Moyenne' : 'Faible'}</span></div><div>Prix : ${p.basePrice} €</div><div class="demand-bar-large"><div class="demand-bar-large-fill" style="width:${pct}%;background:${l === 'high' ? 'var(--green)' : l === 'medium' ? 'var(--amber)' : 'var(--red)'}"></div></div><div class="demand-stats"><span>Demande : ${d}/lot</span><span>${pct}%</span></div></div>`; }).join('');
}

function renderSellPanel() {
  document.getElementById('sell-cash').textContent = fmt(S.cash); document.getElementById('sell-demand-mult').textContent = Math.round(S.demandMult * 100) + '%';
  document.getElementById('sell-grid').innerHTML = products.map(p => { let s = S.productStocks[p.id] || 0, dis = s === 0; let d = S.productDemands[p.id] || p.baseDemand; return `<div class="sell-card ${dis ? 'disabled' : ''}"><div class="sell-top"><span>${p.name}</span><span class="sell-stock-chip ${s > 0 ? 'has' : 'empty'}">${s}</span></div><div class="price-section"><input class="price-input" id="sprice-${p.id}" value="${p.basePrice}" min="1" oninput="onPriceChange(${p.id})" ${dis ? 'disabled' : ''}><div class="demand-preview"><div class="demand-bar-wrap"><div class="demand-bar-fill" id="dbar-${p.id}" style="width:${Math.min(100, Math.round(d / p.baseDemand * 100))}%"></div></div><span id="dval-${p.id}">${d}/lot</span></div></div><div class="sell-qty-row"><input class="sell-qty-input" id="sqty-${p.id}" placeholder="Qté" min="1" max="${s}" oninput="onSellQtyChange(${p.id})" ${dis ? 'disabled' : ''}><span id="stotal-${p.id}">= 0 €</span></div><div id="stax-${p.id}">Taxe 20% = 0 €</div><button class="sell-btn" onclick="sellProduct(${p.id})" ${dis ? 'disabled' : ''}>Vendre</button></div>`; }).join('');
}

function onPriceChange(id) { let p = products.find(x => x.id == id); if (!p) return; let d = S.productDemands[p.id] || p.baseDemand, pct = Math.min(100, Math.round(d / p.baseDemand * 100)); document.getElementById(`dbar-${id}`).style.width = pct + '%'; document.getElementById(`dval-${id}`).textContent = `${d}/lot`; onSellQtyChange(id); }
function onSellQtyChange(id) { let p = products.find(x => x.id == id); if (!p) return; let pr = Math.max(1, parseInt(document.getElementById(`sprice-${id}`)?.value) || 1), q = parseInt(document.getElementById(`sqty-${id}`)?.value) || 0; q = Math.min(q, S.productStocks[p.id] || 0); let t = q * pr, tax = Math.round(t * TAX_RATE); document.getElementById(`stotal-${id}`).textContent = `= ${t.toLocaleString('fr-FR')} €`; document.getElementById(`stax-${id}`).textContent = `Taxe = ${tax.toLocaleString('fr-FR')} €`; }

function sellProduct(id) {
  let p = products.find(x => x.id == id); if (!p) return; let s = S.productStocks[p.id] || 0; if (!s) return; let q = Math.min(s, parseInt(document.getElementById(`sqty-${id}`)?.value) || 0); if (!q) return;
  let d = S.productDemands[p.id] || p.baseDemand; if (q > d) { toast(`Demande insuffisante ! (max: ${d})`, 'err'); return; }
  let pr = Math.max(1, parseInt(document.getElementById(`sprice-${id}`)?.value) || p.basePrice), rev = q * pr;
  pendingTaxes += Math.round(rev * TAX_RATE); S.productStocks[p.id] = s - q; S.productDemands[p.id] = d - q; S.cash += rev; S.totalEarned += rev;
  logAcc(`Vente ${q}× ${p.name} : +${fmt(rev)}`, 'pos'); updateUI(); renderSellPanel(); pushChart(); checkContractProgress(); if (document.getElementById('panel-demand').classList.contains('open')) renderDemandPanel();
}

function renderStockPanel() {
  let a = document.querySelector('#panel-stock .tab.active')?.textContent;
  if (a?.includes('Matières')) { document.getElementById('stock-materials-body').innerHTML = MATERIALS.map(m => { let s = S.materialsStock[m.name] || 0; return `<tr><td>${m.icon} ${m.name}</td><td>${s}</td><td>${S.prices[m.name]} €</td><td>${(s * S.prices[m.name]).toLocaleString('fr-FR')} €</td></tr>`; }).join(''); }
  else if (a?.includes('N2')) { let ps = products.filter(p => p.complexity <= 3); document.getElementById('stock-productsN2-body').innerHTML = ps.map(p => { let s = S.productStocks[p.id] || 0; return `<tr><td>${p.name}</td><td>${s}</td><td>${p.basePrice} €</td><td>${(s * p.basePrice).toLocaleString('fr-FR')} €</td></tr>`; }).join(''); }
  else if (a?.includes('N3')) { let ps = products.filter(p => p.complexity > 3 && p.complexity <= 6); document.getElementById('stock-productsN3-body').innerHTML = ps.map(p => { let s = S.productStocks[p.id] || 0; return `<tr><td>${p.name}</td><td>${s}</td><td>${p.basePrice} €</td><td>${(s * p.basePrice).toLocaleString('fr-FR')} €</td></tr>`; }).join(''); }
  else if (a?.includes('N4')) { let ps = products.filter(p => p.complexity > 6); document.getElementById('stock-productsN4-body').innerHTML = ps.map(p => { let s = S.productStocks[p.id] || 0; return `<tr><td>${p.name}</td><td>${s}</td><td>${p.basePrice} €</td><td>${(s * p.basePrice).toLocaleString('fr-FR')} €</td></tr>`; }).join(''); }
  else { document.getElementById('stock-products-body').innerHTML = products.map(p => { let s = S.productStocks[p.id] || 0; return `<tr><td>${p.name}</td><td>${s}</td><td>${p.basePrice} €</td><td>${(s * p.basePrice).toLocaleString('fr-FR')} €</td></tr>`; }).join(''); }
}

function switchStockTab(t) { document.querySelectorAll('#panel-stock .tab').forEach(x => x.classList.remove('active')); event.target.classList.add('active'); ['materials', 'products', 'productsN2', 'productsN3', 'productsN4'].forEach(x => document.getElementById(`stock-${x}`).style.display = x === t ? 'block' : 'none'); renderStockPanel(); }

function renderEmployeePanel() {
  document.getElementById('emp-total').textContent = S.employees; document.getElementById('emp-busy').textContent = usedEmployeesCount(); document.getElementById('emp-free').textContent = freeEmployeesCount(); document.getElementById('emp-training').textContent = getEmployeesInTrainingCount();
  document.getElementById('employee-grid').innerHTML = employees.map((e, i) => { resetVacationIfNeeded(e); e.happiness = calculateEmployeeHappiness(e); let l = e.happiness >= 70 ? 'high' : e.happiness >= 40 ? 'medium' : 'low'; return `<div class="employee-card" style="${e.inTraining ? 'opacity:0.7;border-color:var(--purple)' : ''}"><div class="employee-name"><span>${e.genderIcon}</span> ${e.name}${e.inTraining ? ' 📚' : ''}</div><div class="employee-stat"><span>Poste</span><span>${e.job}</span></div><div class="employee-stat"><span>Salaire</span><span>${e.wage} €/j</span></div><div class="skills-section"><div class="skill-row"><span class="skill-label">Efficacité</span><div class="skill-bar"><div class="skill-fill efficiency" style="width:${e.efficiency}%"></div></div><span class="skill-value">${e.efficiency}%</span></div><div class="skill-row"><span class="skill-label">Rapidité</span><div class="skill-bar"><div class="skill-fill speed" style="width:${e.speed}%"></div></div><span class="skill-value">${e.speed}%</span></div></div><div class="employee-happiness"><div class="employee-happiness-header"><span>😊 Bonheur</span><span>${e.happiness}%</span></div><div class="employee-happiness-bar"><div class="employee-happiness-fill ${l}" style="width:${e.happiness}%"></div></div></div><div class="vacation-info"><div class="employee-stat"><span>Vacances</span><span>${e.vacationDaysLeft} j</span></div>${!e.inTraining ? `<button class="tb-btn" style="width:100%;margin-top:8px" onclick="giveVacation(${i})">🏖️ 1 semaine</button><button class="tb-btn danger" style="width:100%;margin-top:4px" onclick="fireSpecificEmployee(${i})">👋 Licencier</button>` : '<div style="text-align:center;padding:8px;color:var(--purple)">📚 En formation</div>'}</div></div>`; }).join(''); updateHappinessBar();
}

function switchEmployeeTab(t) { document.querySelectorAll('#panel-employees .tabs:first-child .tab').forEach(x => x.classList.remove('active')); event.target.classList.add('active'); document.getElementById('employee-list-tab').style.display = t === 'list' ? 'block' : 'none'; document.getElementById('employee-jobs-tab').style.display = t === 'jobs' ? 'block' : 'none'; document.getElementById('employee-training-tab').style.display = t === 'training' ? 'block' : 'none'; document.getElementById('employee-bonus-tab').style.display = t === 'bonus' ? 'block' : 'none'; if (t === 'list') renderEmployeePanel(); else if (t === 'jobs') renderJobsTab(); else if (t === 'training') renderTrainingTab(); else if (t === 'bonus') renderBonusTab(); }

function switchJobsSubTab(t) { document.querySelectorAll('#employee-jobs-tab .tabs .tab').forEach(x => x.classList.remove('active')); event.target.classList.add('active'); document.getElementById('jobs-maintenance').style.display = t === 'maintenance' ? 'block' : 'none'; document.getElementById('jobs-management').style.display = t === 'management' ? 'block' : 'none'; renderJobsTab(); }

function renderJobsTab() {
  let av = employees.map((e, i) => ({ ...e, index: i })).filter(e => e.job === JOB_TYPES.NONE && !e.inTraining);
  let rd = (t) => document.getElementById(`dropdown-content-${t}`).innerHTML = av.map(e => `<label class="dropdown-item"><input type="checkbox" value="${e.index}" onchange="updateSelectedEmployees('${t}',${e.index},this.checked)"><span class="emp-info"><span class="emp-name">${e.genderIcon} ${e.name}</span><span class="emp-details">Eff:${e.efficiency}% Vit:${e.speed}% · ${e.wage}€/j</span></span></label>`).join('');
  rd('maintenance'); rd('cleaner'); rd('handler'); rd('lineManager'); rd('siteManager');
  document.getElementById('current-maintenance').textContent = employees.filter(e => e.job === JOB_TYPES.MAINTENANCE).map(e => e.name).join(', ') || 'Aucun';
  document.getElementById('current-cleaners').textContent = employees.filter(e => e.job === JOB_TYPES.CLEANER).map(e => e.name).join(', ') || 'Aucun';
  document.getElementById('current-handlers').textContent = employees.filter(e => e.job === JOB_TYPES.HANDLER).map(e => e.name).join(', ') || 'Aucun';
  document.getElementById('current-lineManagers').textContent = employees.filter(e => e.job === JOB_TYPES.LINE_MANAGER).map(e => e.name).join(', ') || 'Aucun';
  document.getElementById('current-siteManagers').textContent = employees.filter(e => e.job === JOB_TYPES.SITE_MANAGER).map(e => e.name).join(', ') || 'Aucun';
}

function renderMachinesPanel() {
  document.getElementById('mach-total').textContent = machines.length; document.getElementById('mach-functional').textContent = getFunctionalMachinesCount(); document.getElementById('mach-broken').textContent = getBrokenMachinesCount();
  document.getElementById('machine-grid').innerHTML = machines.map(m => { let ir = !!repairsInProgress[m.id], r = repairsInProgress[m.id], rh = ''; if (ir) { let rem = Math.max(0, r.endTime - Date.now()), pct = ((REPAIR_TIME_REAL - rem) / REPAIR_TIME_REAL) * 100, gm = rem * REAL_TO_GAME_RATIO / 1000; rh = `<div class="repair-progress"><div class="repair-header"><span>🔧 Réparation</span><span id="repair-time-${m.id}">${Math.floor(gm / 60)}:${String(Math.floor(gm % 60)).padStart(2, '0')}</span></div><div class="repair-bar"><div class="repair-fill" id="repair-fill-${m.id}" style="width:${pct}%"></div></div></div>`; } return `<div class="machine-card ${m.broken ? 'broken' : ''} ${m.stopped ? 'stopped' : ''}"><div class="machine-header"><input class="machine-name-input" value="${m.name}" onchange="renameMachine(${m.id},this.value)"><span class="machine-status ${m.broken ? 'broken' : m.stopped ? 'stopped' : 'ok'}">${m.broken && !ir ? '🔴 Panne' : m.broken ? '🔧 Réparation' : m.stopped ? '⏸ Arrêtée' : '🟢 OK'}</span></div><div class="machine-usage"><div class="machine-usage-bar"><div class="machine-usage-fill ${m.usage >= 70 ? 'high' : m.usage >= 30 ? 'medium' : 'low'}" style="width:${m.usage}%"></div></div><div class="machine-usage-text"><span>Utilisation</span><span>${m.usage}/${MACHINE_MAX_USAGE}</span></div></div>${rh}<div class="machine-actions">${m.broken && !ir ? `<button class="tb-btn amber" onclick="startRepair(${m.id})">🔧 Réparer (500€)</button>` : ''}${!m.broken ? `<button class="tb-btn ${m.stopped ? 'green' : 'amber'}" onclick="toggleMachineStop(${m.id})">${m.stopped ? '▶ Redémarrer' : '⏸ Arrêter'}</button>` : ''}</div></div>`; }).join('');
}

function switchMachinesTab(t) { document.querySelectorAll('#machines-tabs .tab').forEach(x => x.classList.remove('active')); event.target.classList.add('active'); ['basic', 'advanced', 'pro', 'complex', 'specific'].forEach(x => document.getElementById(`machines-${x}`).style.display = x === t ? 'block' : 'none'); if (t === 'basic') renderMachinesPanel(); }
function renameMachine(id, n) { let m = machines.find(x => x.id === id); if (m) m.name = n; }

function updateDashboardWidgets() {
  document.getElementById('dw-mok').textContent = getAvailableMachines().length; document.getElementById('dw-mbr').textContent = getBrokenMachinesCount();
  let ml = document.getElementById('dw-machines-list'); if (ml) { let maxVisible = 15; let visibleMachines = machines.slice(0, maxVisible); ml.innerHTML = visibleMachines.map(m => `<div class="machine-summary-row"><span>${m.name}</span><span class="machine-badge ${m.broken ? 'broken' : m.stopped ? 'broken' : 'ok'}">${m.broken ? '🔴' : m.stopped ? '⏸' : '🟢'}</span></div>`).join(''); if (machines.length > maxVisible) { ml.innerHTML += `<button class="show-all-machines-btn" onclick="openPanel('machines')">Voir toutes les machines (${machines.length}) →</button>`; } }
  let sl = document.getElementById('dw-stocks-list'); if (sl) { let ws = products.filter(p => (S.productStocks[p.id] || 0) > 0); sl.innerHTML = ws.length ? ws.slice(0, 6).map(p => `<div class="stock-summary-row"><span>${p.name}</span><span>${S.productStocks[p.id]} u.</span></div>`).join('') : '<div class="empty-widget">Aucun stock</div>'; }
  let qs = document.getElementById('dw-quicksell-list'); if (qs) { let wp = products.filter(p => (S.productStocks[p.id] || 0) > 0); qs.innerHTML = wp.length ? wp.slice(0, 5).map(p => `<div class="quick-sell-row"><span>${p.name}</span><span>${S.productStocks[p.id]}</span><input class="quick-sell-input" id="qs-${p.id}" value="1" min="1" max="${S.productStocks[p.id]}"><button class="quick-sell-btn" onclick="quickSellProduct(${p.id})">Vendre</button></div>`).join('') : '<div class="empty-widget">Aucun</div>'; }
}

function quickSellProduct(id) { let p = products.find(x => x.id == id); if (!p) return; let s = S.productStocks[p.id] || 0; if (!s) return; let q = parseInt(document.getElementById(`qs-${id}`)?.value) || 1; q = Math.min(s, q); let d = S.productDemands[p.id] || p.baseDemand; if (q > d) { toast(`Demande insuffisante ! (max: ${d})`, 'err'); return; } let r = q * p.basePrice; pendingTaxes += Math.round(r * TAX_RATE); S.productStocks[p.id] = s - q; S.productDemands[p.id] = d - q; S.cash += r; S.totalEarned += r; updateUI(); pushChart(); checkContractProgress(); if (document.getElementById('panel-demand').classList.contains('open')) renderDemandPanel(); }

function updateProductionProgressBars() { Object.entries(S.activeProductions).forEach(([id, a]) => { let p = products.find(x => x.id == id); if (!p) return; let e = Date.now() - a.cycleStartTime, prog = Math.min(100, (e / p.productionTimeReal) * 100), f = document.getElementById(`prod-fill-${id}`); if (f) f.style.width = prog + '%'; }); }

function openPanel(n) {
  document.getElementById(`panel-${n}`).classList.add('open');
  if (n === 'market') renderMarket(); else if (n === 'production') renderProdPanel(); else if (n === 'sell') renderSellPanel(); else if (n === 'demand') renderDemandPanel(); else if (n === 'stock') renderStockPanel(); else if (n === 'employees') renderEmployeePanel(); else if (n === 'machines') renderMachinesPanel(); else if (n === 'contracts') renderContractsPanel(); else if (n === 'accounting') { initAccountingChart(); renderAccountingPanel(); } else if (n === 'bank') updateLoanDisplay(1000);
}

function closePanel(n) {
  if (n === 'market' && Object.keys(cart).length > 0) {
    let itemsHtml = Object.entries(cart).map(([m, q]) => { let p = S.prices[m]; return `<div style="display:flex;justify-content:space-between;padding:4px 0"><span>${MAT_MAP[m]?.icon || ''} ${m} ×${q}</span><span>${(p * q).toLocaleString('fr-FR')} €</span></div>`; }).join('');
    let total = Object.entries(cart).reduce((s, [m, q]) => s + S.prices[m] * q, 0);
    let msg = `<div style="margin-bottom:16px"><b>Votre panier :</b></div>${itemsHtml}<div style="display:flex;justify-content:space-between;margin-top:12px;padding-top:8px;border-top:1px solid var(--border)"><b>Total</b><b>${total.toLocaleString('fr-FR')} €</b></div><p style="margin-top:16px;color:var(--muted)">Que voulez-vous faire ?</p>`;
    let actions = `<button class="tb-btn green" style="flex:1" id="cart-validate">✅ Valider</button><button class="tb-btn danger" style="flex:1" id="cart-clear">🗑️ Vider</button><button class="tb-btn" style="flex:1" id="cart-keep">📦 Garder</button>`;
    showConfirm('Quitter le marché', msg, () => {}, actions);
    document.getElementById('cart-validate').onclick = () => { checkoutCart(); closeConfirm(); document.getElementById(`panel-${n}`).classList.remove('open'); };
    document.getElementById('cart-clear').onclick = () => { clearCart(); closeConfirm(); document.getElementById(`panel-${n}`).classList.remove('open'); };
    document.getElementById('cart-keep').onclick = () => { closeConfirm(); document.getElementById(`panel-${n}`).classList.remove('open'); };
  } else { document.getElementById(`panel-${n}`).classList.remove('open'); }
}